### ISSUE TITLE
Bane of Arthropods VII book in item list ignore neuec

### ISSUE THREAD

**Issue by SkyNalix** [NotEnoughUpdates/NotEnoughUpdates-REPO#636] opened 2021-10-18 18:19 UTC
When you search for the book Bane of Arthropods VII, it always appear in default blue color
But the neuec is applied when looking at the Max Enchanted Book & on items, so i suppose it's only a repo issue

**Comment by jani270** [comment] 2021-11-01 08:27
Issue should be fixed with #646, if the issue is still there please ping me on discord.

**Closed by jani270** 2021-11-01 08:27 UTC
